Alternative solvent extension for the black oil model.
OPM/opm-models pull request #628
Opened 2020-10-12 09:17 UTC by osae

A first version, depending on corresponding pr for opm-simulators (extboSimulators) and opm-common (kwPVTEXTBO).

2020-10-12 09:19 UTC, akva2 commented on opm/models/blackoil/blackoilextbomodules.hh
> +    typedef typename GET_PROP_TYPE(TypeTag, Scalar) Scalar;
please avoid property macros, see https://github.com/OPM/opm-models/commit/2a3389100016c25fdb679983dec380f23f22a52d

2020-10-14 09:13 UTC, totto82 requested changes
Thanks for the contribution. Most of my comments are cosmetic. But the two TODOs I think needs to be addressed before merging.

2020-10-14 09:13 UTC, totto82 commented on opm/models/blackoil/blackoilextbomodules.hh
> +    void zFractionUpdate_(const ElementContext& elemCtx,
The text is is old I think. 
zFractionUpdate_ updates the internal variable stored in the iq of the extended blackoil model. Maybe we should merge the code in zPvtUpdate_ in here and change the name to extendedBlackoilUpdate(....)

2020-10-14 09:13 UTC, totto82 commented on opm/models/blackoil/blackoilextbomodules.hh
> +           if (zFraction_ > zLim) {
Is the zLim value valid for different models?

2020-10-14 09:13 UTC, totto82 commented on opm/models/blackoil/blackoilextbomodules.hh
> +
This TODO needs to be addressed before merging. The value is not generic for different input data.

2020-10-14 09:13 UTC, totto82 commented on opm/models/blackoil/blackoilextbomodules.hh
> +
same here.

2020-10-14 09:13 UTC, totto82 commented on opm/models/blackoil/blackoilextbomodules.hh
> + */
Add a reference to the ecmor paper

2020-11-10 14:58 UTC, totto82 commented
Thanks looks good. If jenkins is happy this can me merged.

2020-11-18 09:05 UTC, totto82 commented on opm/models/blackoil/blackoilextbomodules.hh
> +    {
These input variables are not used. I suggest you just removed them and change the call site

2020-11-18 13:01 UTC, merged

2020-11-18 18:17 UTC, bska commented on opm/models/blackoil/blackoilextbomodules.hh
> +        bz_ = ExtboModule::bg(pvtRegionIdx, fs.pressure(oilPhaseIdx), 0.99);
@osae , @totto82 : Is this call supposed to go to the `Scalar` overload or to the `Evaluation` overload?

2020-11-19 07:30 UTC, akva2 commented
This broke the build, https://ci.opm-project.org/job/opm-models/83/console

2020-11-19 07:37 UTC, bska commented
> This broke the build

For what it's worth, I have a local fix but it depends on the answer to my earlier [question](https://github.com/OPM/opm-models/pull/628#pullrequestreview-533746691).

2020-11-19 07:54 UTC, totto82 commented on opm/models/blackoil/blackoilextbomodules.hh
> +        bz_ = ExtboModule::bg(pvtRegionIdx, fs.pressure(oilPhaseIdx), 0.99);
It should be Evaluation.

2020-11-19 07:55 UTC, totto82 commented
Why wasn't this cached by Jenkins in the first place. I can provide a fix.

2020-11-19 07:57 UTC, akva2 commented
ou only built from the downstream, thus the tests in opm-model are not built.

2020-11-19 07:58 UTC, totto82 commented
I didn't know. Lucky I haven't broke more. So it is safer to build it from opm-common

2020-11-19 07:59 UTC, akva2 commented
as a general rule you trigger from the first repo having a change.

2020-11-19 08:03 UTC, bska commented
> I can provide a fix.

Like I said, I already have a fix in place that's ready to go once I know the answer to which overload the call to `bg()` with a constant `0.99` is supposed to go to&mdash;the `Scalar` one or the `Evaluation` one.

2020-11-19 08:17 UTC, totto82 commented
@bska It should  be Evaluation.  Then I will wait for your fix.

2020-11-19 08:35 UTC, bska commented
> It should be Evaluation.

Very good.  I've submitted PR #636 to address this issue.