Add support for directional relative permeabilities
OPM/opm-models pull request #714
Opened 2022-09-01 19:43 UTC by hakonhagland

2022-09-01 19:50 UTC, hakonhagland commented
jenkins build this opm-material=532 opm-common=3113 please

2022-09-15 06:41 UTC, atgeirr requested changes
What I looked at seems good, I just have a few questions and minor requests.

2022-09-15 06:41 UTC, atgeirr commented on opm/models/blackoil/blackoilintensivequantities.hh
> +    void updateRelperms(const Problem& problem, const MaterialLawParams& materialParams, unsigned globalSpaceIdx)
When it is spread across two functions, it is not easy to see that mobility_ and dirMob_ gets updated here. What about making this a static function and passing mobility_ and dirMob_ to it, that way it is obvious at the call site that those variables get updated?

2022-09-15 06:41 UTC, atgeirr commented on opm/models/discretization/ecfv/ecfvstencil.hh
> +        FaceDir::DirEnum dirId() const
For my current work on boundary conditions, it would be very useful if dirId() returned the underlying int instead, as I need to distinguish between the XMin and XPlus cases. Could we make that change, and add a free function faceDirFromDirId() with the implementation below?

2022-09-15 06:41 UTC, atgeirr commented on opm/models/blackoil/blackoilintensivequantities.hh
> +    std::shared_ptr<DirectionalMobility> dirMob_;
I assume this is a shared_ptr and not a unique_ptr to keep the class copyable. But I think that changes the semantics of the class in a nontrivial way, as we will then not get a fully independent copy anymore. I am not set against it, but have you looked at the places where IQs are copied and checked that this is ok?

If we want to preserve deep copy semantics with a smart pointer it is possible, the Thor library has (or at least used to have) a CopiedPtr template that implemented it: https://bromeon.ch/libraries/thor/tutorials/v1.1/smartptr.html

Not sure that is necessary though.

2022-09-16 07:36 UTC, hakonhagland commented on opm/models/blackoil/blackoilintensivequantities.hh
> +    void updateRelperms(const Problem& problem, const MaterialLawParams& materialParams, unsigned globalSpaceIdx)
Good idea! See update.

2022-09-16 07:36 UTC, hakonhagland commented on opm/models/discretization/ecfv/ecfvstencil.hh
> +        FaceDir::DirEnum dirId() const
Yes, see update.

2022-09-16 07:37 UTC, hakonhagland commented on opm/models/blackoil/blackoilintensivequantities.hh
> +    std::shared_ptr<DirectionalMobility> dirMob_;
Yes! That was to make the IQs copyable. I am not sure if there is an easy way to find all the places where the copy constructor and assignment operator for the IQ is used. I checked some files and looked at the compiler error messages and found one place in fvbaseelmentcontext.hh where they are copied: see updateIntensitiveQuantities_() at [line 562](https://github.com/OPM/opm-models/blob/331a3de9602691601916906f7cd19ccd13cce772/opm/models/discretization/common/fvbaseelementcontext.hh#L562)  and one place where the IQs  are reassigned, see updateStencil() at [line 140](https://github.com/OPM/opm-models/blob/331a3de9602691601916906f7cd19ccd13cce772/opm/models/discretization/common/fvbaseelementcontext.hh#L140). There are probably other places? 

In the updated PR, I changed the shared_ptr to unique_ptr and added a copy constructor and an assignment operator to the BlackOilIntensiveQuantities class.

2022-09-16 07:56 UTC, atgeirr commented on opm/models/blackoil/blackoilintensivequantities.hh
> +    std::shared_ptr<DirectionalMobility> dirMob_;
I think it is not a good solution to add explicitly coded copy constructors and assignment operators. It adds to the maintenance overhead significantly. I am also not sure it is actually correct as implemented here in the copy constructor, it fails to copy most members, this just demonstrates the point that it is hard to maintain.

I think using a copyable smart pointer is the best solution, keeping the copy construction and assigment defaulted. I may have come across as skeptical of the shared_ptr, but I think it can be an acceptable solution, as long as we have considered the consequences. A smart pointer with copy semantics is also a fine solution I think, but requires us to create or adopt such a template class.

2022-09-16 07:57 UTC, atgeirr commented on opm/models/discretization/ecfv/ecfvstencil.hh
> +        FaceDir::DirEnum dirId() const
Thanks, I have added the code identically to my own branch too, so it should be easy to rebase one once the other is merged.

2022-09-18 23:45 UTC, hakonhagland commented on opm/models/blackoil/blackoilintensivequantities.hh
> +    std::shared_ptr<DirectionalMobility> dirMob_;
>  It adds to the maintenance overhead significantly

@atgeirr Yes, I agree.

> A smart pointer with copy semantics is also a fine solution I think, but requires us to create or adopt such a template class.

I'll give the "copyable pointer" a try first. In the added commit I try to implement a minimal functionality for a copyable pointer.

2022-09-19 08:09 UTC, atgeirr commented on opm/models/blackoil/blackoilintensivequantities.hh
> +        T& get() const {return *ptr_;}
To be consistent with the unique_ptr interface, it should return the raw pointer instead (`return ptr_.get()`).

2022-09-19 08:11 UTC, atgeirr commented on opm/models/blackoil/blackoilintensivequantities.hh
> +                ptr_ = std::make_unique<T>(other.get());
With get() returning a pointer (see below), this should change to take `*this`.

2022-09-19 08:13 UTC, atgeirr commented on opm/models/blackoil/blackoilintensivequantities.hh
> +            // else {ptr_ = nullptr;} // this is the default construction value
The else branch must be implemented to kill the current pointer. Copying from an empty smart pointer should leave the current object as a similarly empty one, just as in the assignment operator.

2022-09-19 08:15 UTC, atgeirr commented on opm/models/blackoil/blackoilintensivequantities.hh
> +    template <class T>
I would add one more warning to this class template comment: You should never use it polymorphically. (That would require a virtual `clone()` method etc.) It will only ever copy the static class type of the pointed to class.

Also, it should be put in a separate file, and have some unit tests.

2022-09-19 23:33 UTC, hakonhagland commented on opm/models/blackoil/blackoilintensivequantities.hh
> +        T& get() const {return *ptr_;}
Good idea

2022-09-19 23:35 UTC, hakonhagland commented on opm/models/blackoil/blackoilintensivequantities.hh
> +            // else {ptr_ = nullptr;} // this is the default construction value
I thought since we are constructing a new object there will be no current object? Then, the default constructor will apply to the unique_ptr which will initialize it with a nullptr. Anyway, for clarity I have updated the code to use the else branch.

2022-09-19 23:35 UTC, hakonhagland commented on opm/models/blackoil/blackoilintensivequantities.hh
> +    template <class T>
Good idea, I have moved the class to opm-common, see https://github.com/OPM/opm-common/pull/3113 and added some tests..

2022-09-20 06:21 UTC, atgeirr commented on opm/models/blackoil/blackoilintensivequantities.hh
> +            // else {ptr_ = nullptr;} // this is the default construction value
You are correct in that there is no current object, my mistake! Maybe I thought it was a move constructor or something, not sure. But the default constructor is not invoked automatically, so you should always ensure all members are initialized.

2022-09-26 07:10 UTC, merged

2022-09-26 08:08 UTC, bska commented
This PR appears to [break](https://ci.opm-project.org/job/opm-models/155/console) the post-commit build.  Please fix or revert.

2022-09-26 08:26 UTC, totto82 commented
Strange, it was green. Let me first double-check locally. Could there be an issue with the ordering and timing of when this and the PR in opm-material was merged?

2022-09-26 08:26 UTC, hakonhagland commented
> This PR appears to break the post-commit build

I see in the jenkins log:

> [5/119] Building CXX object CMakeFiles/reservoir_blackoil_vcfv.dir/tests/reservoir_blackoil_vcfv.cc.o
FAILED: CMakeFiles/reservoir_blackoil_vcfv.dir/tests/reservoir_blackoil_vcfv.cc.o 

But locally on my machine the test `reservoir_blackoil_vcfv` in opm-models seems not to be built. Any ideas how I can build and test this locally?

2022-09-26 08:43 UTC, bska commented
> locally on my machine the test `reservoir_blackoil_vcfv` in opm-models seems not to be built. Any ideas how I can build and test this locally?

Configure all your module builds with the
```sh
-DBUILD_TESTING:BOOL=True
```
cmake option.

2022-09-26 08:48 UTC, bska commented
> Could there be an issue with the ordering and timing of when this and the PR in opm-material was merged?

I suppose, but I get the same result locally when I include `BUILD_TESTING` in my configuration options.

2022-09-27 04:59 UTC, hakonhagland commented
>Configure all your module builds with the
>
>-DBUILD_TESTING:BOOL=True

@bska Thanks for the information!

> This PR appears to break the post-commit build. Please fix or revert.

This has been addressed in  https://github.com/OPM/opm-models/pull/727. Thanks to @totto82 for ideas on how to solve this.