fix issue when BCPROP is not set initially
OPM/opm-models pull request #833
Opened 2023-10-06 07:47 UTC by totto82

In the current code BCPROP is ignored if it is not set in the first time step. This PR make it possible to set BCPROP later in the schedule.

2023-10-06 07:48 UTC, totto82 commented
jenkins build this opm-simulators=4912 please

2023-10-16 08:41 UTC, totto82 commented
jenkins build this opm-simulators=4912 please

2023-10-18 13:51 UTC, totto82 commented
jenkins build this opm-simulators=4912 please

2023-10-19 09:36 UTC, totto82 commented
The test failure is expected. The current code does not impose the correct bc for the test case. This fixes a bug, but since there is simple workaround (just adding the BCPROP for the initial step), I dont think it needs to be part of the release. Hopefully it can be merged when the release is done.

2023-11-01 07:44 UTC, totto82 commented
jenkins build this opm-simulators=4912 please

2023-11-09 09:17 UTC, totto82 commented
jenkins build this opm-simulators=4912 please

2023-11-10 09:17 UTC, atgeirr requested changes
While I think this is correct, it will likely cause some performance degradation. With this we will always, in every assemble, iterate over all boundary faces even if there are no boundary conditions.

We should make sure that we only build these structures for the boundary faces that will at some point receive a condition, unless you think that is not possible. Maybe we should distinguish between "no condition now" and "no condition ever" in the type enum?

I will review the opm-simulators PR now with a view to this.

2023-11-10 09:17 UTC, atgeirr commented on opm/models/discretization/common/tpfalinearizer.hh
> +                                                    massrate,
Indent.

2023-11-13 09:41 UTC, totto82 commented
Thanks for the review. I added a if(nonTrivialBoundaryConditions). That should take care of the performance overhead if you dont have boundary conditions.

2023-11-13 09:41 UTC, totto82 commented
jenkins build this opm-simulators=4912 please

2023-11-13 11:11 UTC, atgeirr approved these changes

2023-11-13 12:44 UTC, totto82 commented
jenkins build this opm-simulators=4912 update_data please

2023-11-13 14:49 UTC, totto82 commented
jenkins build this opm-simulators=4912 opm-tests=1089 please

2023-11-14 07:45 UTC, totto82 commented
jenkins build this opm-simulators=4912 please

2023-11-14 08:26 UTC, totto82 commented
jenkins build this opm-simulators=4912 update_data please

2023-11-22 08:47 UTC, totto82 commented
jenkins build this opm-simulators=4912 opm-tests=1089 please

2023-11-22 12:40 UTC, merged